trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # ---------- FRONTEND ----------
  - task: UseNode@1
    displayName: "Use Node.js 20.x"
    inputs:
      version: '20.19.0'

  - task: Cache@2
    displayName: Cache npm (frontend)
    inputs:
      key: 'npm | "$(Agent.OS)" | frontend/package-lock.json'
      path: frontend/node_modules
      restoreKeys: |
        npm | "$(Agent.OS)"

  - script: npm ci
    displayName: "Install dependencies (frontend)"
    workingDirectory: frontend

  - script: npm run build
    displayName: "Build frontend"
    workingDirectory: frontend

  # ---------- BACKEND ----------
  - task: JavaToolInstaller@0
    displayName: "Set up Java 17"
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  # Run backend unit tests with clear console output
  - script: >
      mvn -B clean test -DskipITs
      -Dsurefire.printSummary=true
      -Dsurefire.useFile=false
      --no-transfer-progress
    displayName: "Run backend unit tests"
    workingDirectory: backend

  # Publish JUnit results so they appear in the "Tests" tab
  - task: PublishTestResults@2
    displayName: "Publish JUnit results"
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'backend/target/surefire-reports/*.xml'
      mergeTestResults: true
      testRunTitle: 'Backend Unit Tests'
