# azure-pipelines.yml
pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@1
    displayName: "Use Node.js 20.x"
    inputs:
      version: '20.19.0'

  - script: node -v && npm -v
    displayName: "Show Node & npm versions"

  - script: npm ci
    displayName: "Install dependencies"

  - script: npm run build
    displayName: "Build frontend"
