# Trigger this pipeline whenever code is pushed to the 'main' branch
trigger:
  - main

# Use a hosted Ubuntu virtual machine provided by Azure DevOps
pool:
  vmImage: ubuntu-latest

# CHANGE: centralize names you showed in screenshots so we reuse them below
variables:
  webAppName: 'TheLittleThings'             # CHANGE: your App Service name
  azureServiceConnection: 'TheLittleThings' # CHANGE: service connection you created
  artifactName: 'drop'                      # CHANGE: name for the published artifact

steps:
  # Ensure Node.js 20.x is installed which is what is need for the frontend
  - task: UseNode@1
    displayName: "Use Node.js 20.x"
    inputs:
      version: '20.19.0'

  # Cache frontend dependencies to speed up pipeline runs
  - task: Cache@2
    displayName: Cache npm (frontend)
    inputs:
      key: 'npm | "$(Agent.OS)" | frontend/package-lock.json'
      path: frontend/node_modules
      restoreKeys: |
        npm | "$(Agent.OS)"

  # Install frontend dependencies from package-lock.json file
  - script: npm ci
    displayName: "Install dependencies (frontend)"
    workingDirectory: frontend

  # Build the frontend for ready production deployment
  - script: npm run build
    displayName: "Build frontend"
    workingDirectory: frontend

  # CHANGE: copy the built frontend into Spring Boot static assets so the backend can serve it
  # Supports both Vite ("dist") and CRA ("build") output folders.
  - bash: |
      set -e
      OUT=""
      if [ -d "frontend/dist" ]; then OUT="frontend/dist"; fi
      if [ -d "frontend/build" ]; then OUT="frontend/build"; fi
      if [ -z "$OUT" ]; then
        echo "No frontend build output found (expected frontend/dist or frontend/build)"; exit 1
      fi
      rm -rf backend/src/main/resources/static || true
      mkdir -p backend/src/main/resources/static
      cp -r "$OUT/"* backend/src/main/resources/static/
      echo "Copied $OUT -> backend/src/main/resources/static"
    displayName: "COPY frontend → backend static"  # CHANGE: make backend serve the SPA

  # Make sure Java 17 is installed  which is needed for springboot and maven compliation
  - task: JavaToolInstaller@0
    displayName: "Set up Java 17"
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  # CHANGE: cache Maven repo to speed up builds
  - task: Cache@2
    displayName: Cache Maven repository
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      path: $(Pipeline.Workspace)/.m2
      restoreKeys: |
        maven | "$(Agent.OS)"
    # CHANGE: tell Maven to use the cached directory via MAVEN_OPTS
  - script: |
      mvn -B -Dmaven.repo.local=$(Pipeline.Workspace)/.m2 \
        clean test \
        -Dsurefire.printSummary=true \
        -Dsurefire.useFile=false \
        --no-transfer-progress
    displayName: "Run backend unit tests"
    workingDirectory: backend

  # Publish JUnit test results to Azure DevOps
  # This makes tests appear in the "Tests" tab with pass/fail status
  - task: PublishTestResults@2
    displayName: "Publish JUnit results"
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'backend/target/surefire-reports/*.xml'
      mergeTestResults: true
      testRunTitle: 'Backend Unit Tests'

  # CHANGE: package Spring Boot as a fat JAR for App Service (Windows, Java SE)
  - script: |
      mvn -B -Dmaven.repo.local=$(Pipeline.Workspace)/.m2 \
        clean package -DskipTests --no-transfer-progress
    displayName: "Package backend (fat JAR)"
    workingDirectory: backend

  # CHANGE: stage files for Zip Deploy (rename jar to app.jar and add web.config)
  - bash: |
      set -e
      STAGE="$(Build.ArtifactStagingDirectory)"
      mkdir -p "$STAGE"
      # pick first jar in target and rename to app.jar
      JAR=$(ls backend/target/*.jar | head -n 1)
      cp "$JAR" "$STAGE/app.jar"
      # generate web.config for Windows App Service with Java SE
      cat > "$STAGE/web.config" << 'EOF'
      <?xml version="1.0" encoding="utf-8"?>
      <configuration>
        <system.webServer>
          <handlers>
            <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
          </handlers>
          <httpPlatform
            processPath="%JAVA_HOME%\bin\java.exe"
            arguments="-jar %HOME%\site\wwwroot\app.jar --server.port=8080"
            stdoutLogEnabled="true"
            stdoutLogFile="%HOME%\LogFiles\java.log" />
        </system.webServer>
      </configuration>
      EOF
      echo "Staged $(ls -l "$STAGE")"
    displayName: "Stage deployables (app.jar + web.config)"

  # CHANGE: publish the staged folder as a pipeline artifact (useful for debugging/releases)
  - publish: '$(Build.ArtifactStagingDirectory)'
    artifact: $(artifactName)
    displayName: "Publish build artifact"

  # CHANGE: zip the staged files for Zip Deploy
  - bash: |
      cd "$(Pipeline.Workspace)"
      rm -f app.zip
      zip -r app.zip "$(artifactName)"
      echo "Created $(Pipeline.Workspace)/app.zip"
    displayName: "Zip artifact for deployment"

  # CHANGE: deploy to your App Service using the service connection named 'TheLittleThings'
  - task: AzureWebApp@1
    displayName: "Deploy to Azure App Service: $(webAppName)"
    inputs:
      azureSubscription: '$(azureServiceConnection)'     # CHANGE: your service connection
      appName: '$(webAppName)'                           # CHANGE: your App Service name
      package: '$(Pipeline.Workspace)/app.zip'           # CHANGE: zip produced above
      appType: 'webApp'                                  # CHANGE: target a Windows Web App
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    # CHANGE: only deploy from main and only if prior steps succeeded
