spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thelittlethings
    username: postgres
    password: DB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
server:
  port: 8080
