spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db.rlordmqycewqfcljdddh.supabase.co:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:AdvancedSoftwareDev123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
server:
  port: 8081
